"""voices library

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 20:59:52.359295
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_voice_id', sa.String(length=200), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=True),
    sa.Column('recording_mime', sa.String(length=100), nullable=False),
    sa.Column('recording', sa.LargeBinary(), nullable=False),
    sa.Column('consent_by', sa.UUID(), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['consent_by'], ['users.id'], name=op.f('fk_voices_consent_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_voices_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_voices_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_voices_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voices'))
    )
    op.create_index('ix_voices_provider_voice', 'voices', ['provider', 'provider_voice_id'], unique=False)
    op.create_index(op.f('ix_voices_tenant_id'), 'voices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voices_tenant_id'), table_name='voices')
    op.drop_index('ix_voices_provider_voice', table_name='voices')
    op.drop_table('voices')
    # ### end Alembic commands ###
